### ISSUE TITLE
Feature request: Library-ize

### ISSUE THREAD

**Issue by bunchc** [lamw/vghetto-vsphere-automated-lab-deployment#5]
The four scripts share a number of common functions and operations. These can be pulled into functions or modules (whatever the PowerShell word for this is) and be consumed from a central point rather than repeated in each script.

**Comment by lamw** [comment]
Yes, this is something I would like to consolidate not just on the parameters but the number of scripts. I wasn't sure where I was going with this initially, so I kept them separate as the underlying implementation between 6.0/6.5 is quite different. 

There's actually some work being done by @mtboren in this fork [here](https://github.com/mtboren/vghetto-vsphere-automated-lab-deployment_fork/tree/dev) which looks promising. Would love to modularize further so that there's a "base" configuration and others can extend the lab to deploy other things ... not something I've given a lot of thought about yet

**Comment by bunchc** [comment]
The kung-fu in that fork is strong. I'll close this out, and with luck, said fork will integrate this way in time.
