### ISSUE TITLE
NSX requires vCenter based deployment?

### ISSUE THREAD

**Issue by bunchc** [lamw/vghetto-vsphere-automated-lab-deployment#7]
See https://github.com/lamw/vghetto-vsphere-automated-lab-deployment/blob/master/vsphere-6.5-vghetto-standard-lab-deployment.ps1#L585

Is this required, or can you use the vcsa deployed in prior steps?

**Comment by lamw** [comment]
This is required if you're doing "Standard" deployment ... the "Self-Managed" basically deploys everything within the Nested ESXi instances (e.g. double-nesting). The original thinking here was to test out VCHA feature, but I don't think I plan to continue supporting this going further as the implications are huge due to additional resources, performance, etc. 

Even w/NSX support, that was only added to 6.5 Standard deployment, the other flows don't have NSX support.

**Comment by bunchc** [comment]
Yeah. For one reason or another the double nested wasn't working (I think it's my undersized lab). I think it /should/ be possible to use the vcsa that is deployed with the standard lab, and may give that a shot later in the day.

**Comment by lamw** [comment]
If you just want a basic vSphere lab, use the "Standard". The self-managed is only if you're trying to do VCHA and in either scenario, make sure you have enough resources :)
